language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_script:
  - npm prune
after_success:
  - cat ./coverage/lcov.info | /node_modules/coveralls/bin/coveralls.js
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
